# Generated by Django 5.2.5 on 2025-08-12 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('catalog', '0002_globaldiscount_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='شماره سفارش')),
                ('phone_e164', models.CharField(max_length=16, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('shipping_address_json', models.JSONField(verbose_name='آدرس ارسال')),
                ('channel', models.CharField(default='web', max_length=20, verbose_name='کانال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('awaiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شد'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل شد'), ('cancelled', 'لغو شد'), ('refunded', 'مسترد شد')], default='paid', max_length=20, verbose_name='وضعیت')),
                ('subtotal_toman', models.PositiveIntegerField(verbose_name='جمع اقلام')),
                ('discounts_toman', models.PositiveIntegerField(verbose_name='جمع تخفیف\u200cها')),
                ('global_discount_toman', models.PositiveIntegerField(default=0, verbose_name='تخفیف سراسری')),
                ('shipping_fee_toman', models.PositiveIntegerField(verbose_name='هزینه ارسال')),
                ('tax_toman', models.PositiveIntegerField(default=0, verbose_name='مالیات')),
                ('gateway_fee_toman', models.PositiveIntegerField(default=0, verbose_name='کارمزد درگاه')),
                ('refund_amount_toman', models.PositiveIntegerField(default=0, verbose_name='مبلغ استرداد')),
                ('total_payable_toman', models.PositiveIntegerField(verbose_name='مبلغ پرداختی')),
                ('cogs_total_toman', models.PositiveIntegerField(default=0, verbose_name='بهای تمام شده کل')),
                ('contribution_margin_toman', models.IntegerField(default=0, verbose_name='سود ناخالص مشارکتی')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('checkout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='carts.checkout')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_fa_snapshot', models.CharField(max_length=180, verbose_name='نام محصول')),
                ('variant_attrs_snapshot', models.JSONField(blank=True, null=True, verbose_name='مشخصات گونه')),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price_toman', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('line_discount_toman', models.PositiveIntegerField(default=0, verbose_name='تخفیف خط')),
                ('unit_cogs_toman', models.PositiveIntegerField(default=0, verbose_name='بهای تمام شده واحد')),
                ('unit_shipping_cost_toman', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال واحد')),
                ('unit_weight_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن (گرم)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.orderheader')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'درخواست شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('received', 'دریافت شد'), ('refunded', 'مسترد شد'), ('closed', 'بسته شد')], default='requested', max_length=20, verbose_name='وضعیت')),
                ('reason_code', models.CharField(max_length=40, verbose_name='علت')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استرداد')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderheader')),
            ],
            options={
                'verbose_name': 'درخواست مرجوعی',
                'verbose_name_plural': 'درخواست\u200cهای مرجوعی',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('condition_note', models.TextField(blank=True, verbose_name='وضعیت/توضیحات')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderline')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest')),
            ],
            options={
                'verbose_name': 'آیتم مرجوعی',
                'verbose_name_plural': 'آیتم\u200cهای مرجوعی',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل شد'), ('lost', 'مفقود'), ('returned', 'مرجوع')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('carrier', models.CharField(max_length=60, verbose_name='حامل')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('shipping_fee_toman', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن مرسوله (گرم)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.orderheader')),
            ],
            options={
                'verbose_name': 'مرسوله',
                'verbose_name_plural': 'مرسولات',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied_toman', models.PositiveIntegerField(verbose_name='تخفیف اعمال\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='catalog.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.orderheader')),
            ],
            options={
                'verbose_name': 'ثبت استفاده از کوپن',
                'verbose_name_plural': 'ثبت\u200cهای استفاده از کوپن',
                'unique_together': {('coupon', 'order')},
            },
        ),
    ]
