# Generated by Django 5.2.5 on 2025-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name_fa',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name_fa',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام خانوادگی'),
        ),
    ]
