# Generated by Django 5.2.5 on 2025-08-12 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='نام کمپین')),
                ('channel', models.CharField(choices=[('sms', 'پیامک')], default='sms', max_length=10, verbose_name='کانال')),
                ('template', models.TextField(verbose_name='قالب پیام')),
                ('variant', models.CharField(blank=True, max_length=10, verbose_name='ورژن')),
                ('is_transactional', models.BooleanField(default=False, verbose_name='تراکنشی؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کمپین',
                'verbose_name_plural': 'کمپین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد')),
                ('target_url', models.TextField(verbose_name='آدرس مقصد')),
                ('variant', models.CharField(blank=True, max_length=10, verbose_name='ورژن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlinks', to='messaging.campaign')),
            ],
            options={
                'verbose_name': 'کوتاه\u200cکننده لینک',
                'verbose_name_plural': 'کوتاه\u200cکننده\u200cهای لینک',
            },
        ),
        migrations.CreateModel(
            name='MessageOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(max_length=16, verbose_name='شماره مقصد')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('provider', models.CharField(default='amoot', max_length=40, verbose_name='ارائه\u200cدهنده')),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('sent', 'ارسال شد'), ('delivered', 'تحویل شد'), ('failed', 'ناموفق')], default='queued', max_length=10, verbose_name='وضعیت')),
                ('provider_msg_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام نزد ارائه\u200cدهنده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تحویل')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='شکست')),
                ('error_msg', models.TextField(blank=True, verbose_name='متن خطا')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('shortlink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.shortlink')),
            ],
            options={
                'verbose_name': 'پیام خروجی',
                'verbose_name_plural': 'پیام\u200cهای خروجی',
                'indexes': [models.Index(fields=['status', 'provider'], name='messaging_m_status_9c4efa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortLinkClick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان کلیک')),
                ('utm_json', models.JSONField(blank=True, null=True, verbose_name='UTM')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='کاربر-عامل')),
                ('shortlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='messaging.shortlink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کلیک روی لینک کوتاه',
                'verbose_name_plural': 'کلیک\u200cهای لینک کوتاه',
                'indexes': [models.Index(fields=['shortlink', 'clicked_at'], name='messaging_s_shortli_a2d9d4_idx')],
            },
        ),
    ]
