# Generated by Django 5.2.5 on 2025-08-12 09:23

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_globaldiscount_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='شناسه ناشناس')),
                ('currency', models.CharField(default='TOM', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='catalog.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price_snapshot_toman', models.PositiveIntegerField(help_text='فقط برای نمایش', verbose_name='قیمت واحد در لحظه')),
                ('line_discount_toman', models.PositiveIntegerField(default=0, verbose_name='تخفیف خط')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'آیتم سبد',
                'verbose_name_plural': 'آیتم\u200cهای سبد',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'شروع شده'), ('abandoned', 'ناتمام'), ('ordered', 'سفارش شد')], default='started', max_length=12)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('shipping_address_json', models.JSONField(verbose_name='آدرس ارسال (JSON)')),
                ('delivery_option', models.CharField(max_length=40, verbose_name='روش ارسال')),
                ('payment_method', models.CharField(default='zarrinpal', max_length=40, verbose_name='روش پرداخت')),
                ('items_subtotal_toman', models.PositiveIntegerField(verbose_name='جمع اقلام')),
                ('discounts_total_toman', models.PositiveIntegerField(verbose_name='جمع تخفیف\u200cها')),
                ('global_discount_toman', models.PositiveIntegerField(default=0, verbose_name='تخفیف سراسری')),
                ('shipping_fee_toman', models.PositiveIntegerField(verbose_name='هزینه ارسال')),
                ('payable_toman', models.PositiveIntegerField(verbose_name='مبلغ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='carts.cart')),
            ],
            options={
                'verbose_name': 'تسویه حساب',
                'verbose_name_plural': 'تسویه حساب\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='carts_cart_user_id_f43479_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['anonymous_id'], name='carts_cart_anonymo_594170_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['status'], name='carts_check_status_0db797_idx'),
        ),
    ]
