# Generated by Django 5.2.5 on 2025-08-12 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(default='zarrinpal', max_length=40, verbose_name='درگاه')),
                ('status', models.CharField(choices=[('initiated', 'آغاز شده'), ('authorized', 'مجاز'), ('captured', 'کامل پرداخت شد'), ('failed', 'ناموفق'), ('refunded', 'مسترد')], default='initiated', max_length=20, verbose_name='وضعیت')),
                ('amount_toman', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('gateway_fee_toman', models.PositiveIntegerField(default=0, verbose_name='کارمزد')),
                ('authority', models.CharField(max_length=100, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='RefID')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ خام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.orderheader')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
