# Generated by Django 5.2.5 on 2025-08-12 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='نام انبار')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand', models.IntegerField(default=0, verbose_name='موجودی')),
                ('reserved', models.IntegerField(default=0, verbose_name='رزرو شده')),
                ('reorder_level', models.IntegerField(blank=True, null=True, verbose_name='حد آستانه سفارش')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_id', models.UUIDField(db_index=True, verbose_name='شناسه سبد')),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'رزرو موجودی',
                'verbose_name_plural': 'رزروهای موجودی',
                'indexes': [models.Index(fields=['variant', 'expires_at'], name='inventory_s_variant_cdf27d_idx')],
            },
        ),
    ]
