# Generated by Django 5.2.5 on 2025-08-12 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_globaldiscount_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('units_on_hand', models.IntegerField(verbose_name='موجودی')),
                ('inventory_value_toman', models.BigIntegerField(verbose_name='ارزش موجودی (تومان)')),
                ('sell_through_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ فروش')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'عکس روزانه موجودی',
                'verbose_name_plural': 'عکس\u200cهای روزانه موجودی',
                'indexes': [models.Index(fields=['snapshot_date'], name='analytics_d_snapsho_e1d29b_idx'), models.Index(fields=['variant'], name='analytics_d_variant_0e1566_idx')],
                'unique_together': {('snapshot_date', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='DailyUserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='تعداد سفارش')),
                ('total_spend_toman', models.BigIntegerField(default=0, verbose_name='مجموع هزینه (تومان)')),
                ('first_purchase_at', models.DateTimeField(blank=True, null=True, verbose_name='اولین خرید')),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین خرید')),
                ('rfm_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز RFM')),
                ('churn_risk', models.CharField(blank=True, max_length=10, null=True, verbose_name='ریسک ریزش')),
                ('lifetime_cogs_toman', models.BigIntegerField(default=0, verbose_name='مجموع بهای تمام\u200cشده')),
                ('preferred_categories', models.JSONField(blank=True, null=True, verbose_name='دسته\u200cهای محبوب (IDs)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عکس روزانه کاربر',
                'verbose_name_plural': 'عکس\u200cهای روزانه کاربر',
                'indexes': [models.Index(fields=['snapshot_date'], name='analytics_d_snapsho_183e3b_idx'), models.Index(fields=['user'], name='analytics_d_user_id_5e94e4_idx')],
                'unique_together': {('snapshot_date', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='نام رویداد')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='زمان وقوع')),
                ('anonymous_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('utm_json', models.JSONField(blank=True, null=True, verbose_name='UTM')),
                ('properties', models.JSONField(blank=True, null=True, verbose_name='خصوصیات')),
                ('sent_to_ga', models.BooleanField(default=False, verbose_name='ارسال به GA4')),
                ('sent_to_mixpanel', models.BooleanField(default=False, verbose_name='ارسال به Mixpanel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', 'timestamp'], name='analytics_e_name_59ee5e_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_e_user_id_2dcfc8_idx'), models.Index(fields=['anonymous_id', 'timestamp'], name='analytics_e_anonymo_c9512a_idx')],
            },
        ),
    ]
