# Generated by Django 5.2.5 on 2025-08-12 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedWeight',
            fields=[
                ('grams', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'وزن مجاز (گرم)',
                'verbose_name_plural': 'وزن\u200cهای مجاز (گرم)',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام برند')),
                ('slug_en', models.SlugField(max_length=140, unique=True, verbose_name='اسلاگ انگلیسی')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255, verbose_name='مسیر فایل')),
                ('alt_fa', models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام دسته')),
                ('slug_en', models.SlugField(max_length=140, unique=True, verbose_name='اسلاگ انگلیسی')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=180, verbose_name='نام محصول')),
                ('slug_en', models.SlugField(max_length=180, unique=True, verbose_name='اسلاگ انگلیسی')),
                ('short_desc_fa', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('long_desc_fa', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('attributes_json', models.JSONField(blank=True, null=True, verbose_name='ویژگی\u200cها (JSON)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='catalog.mediaasset')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='بارکد')),
                ('grind_type', models.CharField(blank=True, choices=[('whole', 'دانه کامل'), ('extra_fine', 'بسیار ریز'), ('fine', 'ریز'), ('medium', 'متوسط'), ('coarse', 'درشت')], max_length=20, null=True, verbose_name='نوع آسیاب')),
                ('is_default', models.BooleanField(default=False)),
                ('min_qty_per_order', models.PositiveIntegerField(default=1)),
                ('max_qty_per_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_for', to='catalog.mediaasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('weight_grams', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.allowedweight')),
            ],
            options={
                'verbose_name': 'گونه (SKU)',
                'verbose_name_plural': 'گونه\u200cها (SKU)',
            },
        ),
        migrations.CreateModel(
            name='VariantPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_toman', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('compare_at_toman', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت قبل (تومان)')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'قیمت گونه',
                'verbose_name_plural': 'قیمت\u200cهای گونه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx'),
        ),
    ]
