# Generated by Django 5.2.5 on 2025-08-12 09:23

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDiscount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent_off', models.PositiveSmallIntegerField(help_text='0 تا 100', verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'verbose_name': 'تخفیف سراسری',
                'verbose_name_plural': 'تخفیف\u200cهای سراسری',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد')),
                ('type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع')),
                ('value', models.PositiveIntegerField(help_text='تومان برای ثابت، درصد برای درصدی', verbose_name='مقدار')),
                ('min_order_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل جمع سبد')),
                ('max_uses_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده کلی')),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده هر کاربر')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category')),
                ('allowed_products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن\u200cها',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='coupon_code_case_insensitive_unique', violation_error_message='کد کوپن تکراری است.')],
            },
        ),
    ]
