# Generated by Django 5.2.5 on 2025-08-12 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_globaldiscount_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام دسته')),
                ('slug_en', models.SlugField(max_length=140, unique=True, verbose_name='اسلاگ انگلیسی')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسته مقالات',
                'verbose_name_plural': 'دسته\u200cهای مقالات',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=180, verbose_name='عنوان')),
                ('slug_en', models.SlugField(max_length=180, unique=True, verbose_name='اسلاگ انگلیسی')),
                ('body_rich_fa', models.TextField(blank=True, verbose_name='متن صفحه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['title_fa'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=80, unique=True, verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=180, verbose_name='عنوان')),
                ('slug_en', models.SlugField(max_length=180, unique=True, verbose_name='اسلاگ انگلیسی')),
                ('excerpt_fa', models.TextField(blank=True, verbose_name='خلاصه')),
                ('content_rich_fa', models.TextField(blank=True, verbose_name='متن کامل')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='catalog.mediaasset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cms.articlecategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='cms.tag')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSeoDefault',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_title_suffix_fa', models.CharField(blank=True, max_length=120, verbose_name='پسوند عنوان سایت')),
                ('default_meta_description_fa', models.CharField(blank=True, max_length=300, verbose_name='توضیح پیش\u200cفرض')),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_default_og', to='catalog.mediaasset')),
            ],
            options={
                'verbose_name': 'سئو پیش\u200cفرض سایت',
                'verbose_name_plural': 'سئوهای پیش\u200cفرض سایت',
            },
        ),
        migrations.CreateModel(
            name='ArticleProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_products', to='cms.article')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_articles', to='catalog.product')),
            ],
            options={
                'verbose_name': 'ارتباط مقاله و محصول',
                'verbose_name_plural': 'ارتباط\u200cهای مقاله و محصول',
                'unique_together': {('article', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('product', 'محصول'), ('category', 'دسته'), ('article', 'مقاله'), ('page', 'صفحه')], max_length=20, verbose_name='نوع')),
                ('entity_id', models.UUIDField(db_index=True, verbose_name='شناسه موجودیت')),
                ('meta_title_fa', models.CharField(blank=True, max_length=180, verbose_name='Meta Title')),
                ('meta_description_fa', models.CharField(blank=True, max_length=300, verbose_name='Meta Description')),
                ('meta_robots', models.CharField(blank=True, help_text='مثال: index,follow یا noindex,nofollow', max_length=60, verbose_name='Robots')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL کانونیکال')),
                ('og_title_fa', models.CharField(blank=True, max_length=180, verbose_name='OG Title')),
                ('og_description_fa', models.CharField(blank=True, max_length=300, verbose_name='OG Description')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_og_for', to='catalog.mediaasset')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سئوها',
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
